[project]
name = "ai-sidekick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.34.2",
    "langchain>=0.3.26",
    "langchain-community>=0.3.26",
    "langgraph>=0.4.8",
]
